# Generated by Django 5.2.1 on 2025-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='horas_extra',
            field=models.IntegerField(),
        ),
    ]
