# Generated by Django 5.2.1 on 2025-05-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_rol_horas_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
