# Generated by Django 5.2.1 on 2025-05-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_rol_horas_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='horas_extra',
            field=models.IntegerField(),
        ),
    ]
