# Generated by Django 5.2.1 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_tipoprestamo_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
